version: "3.8"

services:
  backend:
    image: findbeauty/clinic-backend:latest
    container_name: clinic-erp-backend-prod
    restart: unless-stopped
    ports:
      - "3000:3000"

    env_file:
      - ./apps/backend/.env
    networks:
      - clinic-erp-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:3000/docs",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: findbeauty/clinic-frontend:latest
    container_name: clinic-erp-frontend-prod
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3000}
    env_file:
      - ./apps/frontend/.env.local
    depends_on:
      - backend
    networks:
      - clinic-erp-network

networks:
  clinic-erp-network:
    driver: bridge
